230.Add decorator functions to pass click options correctly
NOAA-GFDL/fre-cli pull request #231
Opened 2024-10-29 21:30 UTC by singhd789

- this was needed in order to import fre make scripts successfully when creating pytests

## Describe your changes

## Issue ticket number and link (if applicable)

## Checklist before requesting a review

- [x] I ran my code
- [x] I tried to make my code readable
- [x] I tried to comment my code
- [ ] I wrote a new test, if applicable
- [ ] I wrote new instructions/documentation, if applicable
- [ ] I ran pytest and inspected it's output
- [x] I ran pylint and attempted to implement some of it's feedback

2024-10-30 14:03 UTC, ilaflott commented on fre/make/createCheckout.py
> +def _checkout_create(yamlfile,platform,target,no_parallel_checkout,jobs,execute,verbose):
backwards! this should not have an underscore. Line 107 should

2024-10-30 14:04 UTC, ilaflott commented on fre/make/createCompile.py
> +def _compile_create(yamlfile,platform,target,jobs,parallel,execute,verbose):
see other comment

2024-10-30 14:04 UTC, ilaflott commented on fre/make/createDocker.py
> +def _dockerfile_create(yamlfile,platform,target,execute):
see above

2024-10-30 14:06 UTC, ilaflott requested changes
underscore convention is backwards!

2024-10-30 14:25 UTC, singhd789 commented on fre/make/createDocker.py
> +def _dockerfile_create(yamlfile,platform,target,execute):
ooooop, my bad. Let me fix that

2024-10-30 14:32 UTC, singhd789 commented
> underscore convention is backwards!

@ilaflott Hmmm so when I reverse the underscore convention, I keep getting this: 
```
TypeError: Callback is not a command.
```

2024-10-30 15:20 UTC, ilaflott commented
> > underscore convention is backwards!
> 
> @ilaflott Hmmm so when I reverse the underscore convention, I keep getting this:
> 
> ```
> TypeError: Callback is not a command.
> ```

since it changes a module name, you need to change the name in other places where that old name is imported, is my guess.

this pattern is absolutely doable, most every other subtool currently has it

2024-10-30 17:35 UTC, ilaflott commented
> > > underscore convention is backwards!
> > 
> > 
> > @ilaflott Hmmm so when I reverse the underscore convention, I keep getting this:
> > ```
> > TypeError: Callback is not a command.
> > ```
> 
> since it changes a module name, you need to change the name in other places where that old name is imported, is my guess.
> 
> this pattern is absolutely doable, most every other subtool currently has it

let me note that `fre pp checkout` also has the pattern backwards

2024-10-30 18:07 UTC, rem1776 approved these changes

2024-10-30 18:31 UTC, singhd789 commented
> let me note that `fre pp checkout` also has the pattern backwards... i.e. i'll get on others case about it!

I think I may have done it with ` fre pp configure-yaml ...` as well. 😅

2024-10-31 19:05 UTC, ilaflott approved these changes

2024-10-31 19:05 UTC, merged