224.fre make compile test
NOAA-GFDL/fre-cli pull request #295
Opened 2024-12-16 15:07 UTC by singhd789

## Describe your changes

## Issue ticket number and link (if applicable)

## Checklist before requesting a review

- [x] I ran my code
- [x] I tried to make my code readable
- [x] I tried to comment my code
- [x] I wrote a new test, if applicable
- [ ] I wrote new instructions/documentation, if applicable
- [x] I ran pytest and inspected it's output
- [x] I ran pylint and attempted to implement some of it's feedback

2024-12-26 17:54 UTC, kiihne-noaa reviewed
looks good to me! We discussed a number of these changes last week.

2025-01-08 17:56 UTC, rem1776 requested changes

2025-01-08 17:56 UTC, rem1776 commented on fre/make/tests/test_create_compile.py
> +    assert [Path(f"{OUT}/fremake_canopy/test/null_model_full/{plat}-{targ}/exec/compile.sh").exists(),
I think this should probably also check for the executable file too, the other files might still be there if it failed.

2025-01-08 18:11 UTC, singhd789 commented on fre/make/tests/test_create_compile.py
> +    assert [Path(f"{OUT}/fremake_canopy/test/null_model_full/{plat}-{targ}/exec/compile.sh").exists(),
Thanks for this catch! You're 100% right

2025-01-08 20:46 UTC, singhd789 commented on fre/make/tests/test_create_compile.py
> +    assert [Path(f"{OUT}/fremake_canopy/test/null_model_full/{plat}-{targ}/exec/compile.sh").exists(),
So I can't actually run the full compile here because it needs the checked out source code and the makefile (which are not made in this test). Instead of checking for the executable (because it'll fail and won't be there), I can just mark this one as an expected failure but definitely still check for the log file.

2025-01-08 21:02 UTC, singhd789 commented on fre/make/tests/test_create_compile.py
> +    assert [Path(f"{OUT}/fremake_canopy/test/null_model_full/{plat}-{targ}/exec/compile.sh").exists(),
Ok, I suppose my first though there is already covered by `def test_bad_target_compilelog():`

2025-01-08 21:10 UTC, singhd789 commented on fre/make/tests/test_create_compile.py
> +    assert [Path(f"{OUT}/fremake_canopy/test/null_model_full/{plat}-{targ}/exec/compile.sh").exists(),
Update: I forgot I can just set an assert equal to False

2025-01-13 21:11 UTC, ilaflott commented on fre/make/create_compile_script.py
> +        click.echo("\nCompile script created at " + bldDir + "/compile.sh" + "\n")
why `click.echo` instead of `print` or `logger` ?

2025-01-13 21:13 UTC, ilaflott commented on fre/make/tests/test_create_compile.py
> +    assert Path(f"{OUT}/fremake_canopy/test/null_model_full/{plat}-{targ}/exec/compile.sh").exists()
`f"{OUT}/fremake_canopy/test/null_model_full/{plat}-{targ}/exec/"` could definitely be assigned to its own variable somewhere. unless you wanna edit the path in several places later upon needed to extend/fix something

2025-01-13 21:14 UTC, ilaflott commented on fre/make/tests/test_create_compile.py
> +        create_compile_script.compile_create(yamlfile_path, BAD_PLATFORM, TARGET, 4, 1, False, False)
sometimes functions like this:
```
some_func(arg1_val, arg2_val, arg3_val ...)
```

are nicer when written out like this:
```
some_func(arg1 = arg1_val, 
          arg2 = arg2_val, 
          arg3 = arg3_val ...)
```

2025-01-13 21:15 UTC, singhd789 commented on fre/make/tests/test_create_compile.py
> +    assert Path(f"{OUT}/fremake_canopy/test/null_model_full/{plat}-{targ}/exec/compile.sh").exists()
the platforms and targets sometimes change (test for bad platforms and targets or multi)

2025-01-13 21:16 UTC, ilaflott approved these changes
it works, if needing some cleanup. Granting approval, but the only clarification i'm really wondering: why `click.echo` in `create_compile_script` ?

2025-01-13 21:17 UTC, singhd789 commented on fre/make/create_compile_script.py
> +        click.echo("\nCompile script created at " + bldDir + "/compile.sh" + "\n")
Good point. I think it might be print everywhere else. Bennett made it click.echo, which was a cool thing to keep with click functionalities, but I might change it back to print to keep it consistent with the rest of the code

2025-01-21 19:53 UTC, merged