Sphinx Documentation
NOAA-GFDL/fre-cli pull request #51
Opened 2024-03-18 21:24 UTC by Ciheim

Setting up Sphinx

2024-03-22 00:45 UTC, ceblanton requested changes
Looks good, except I don't like the binary files in git repos. Are they really needed?

2024-03-22 00:45 UTC, ceblanton commented on docs/.doctrees/FAQ.doctree
Is this binary file (and the next few) needed, or is it generated by sphinx as an intermediate file or such?

2024-03-26 16:29 UTC, Ciheim commented on docs/.doctrees/FAQ.doctree
Auto generated and not needed. Removing!

2024-04-02 14:10 UTC, ceblanton approved these changes
This looks great, thank you!

2024-04-02 14:10 UTC, merged